version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8

jobs:
  audit: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://jacoblindstrom.design,https://jacoblindstrom.design/work,https://jacoblindstrom.design/about,https://jacoblindstrom.design/about/resume
      - lighthouse-check/validate-status:
          minAccessibilityScore: "95"
          minPerformanceScore: "90"
          minSeoScore: "85"

workflows:
  test:
    jobs:
      - audit
