version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8

jobs:
  test: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://jacoblindstrom.design,https://jacoblindstrom.design/about,https://jacoblindstrom.design/work,https://jacoblindstrom.design/resume

workflows:
  test:
    jobs:
      - Accessibility and Performance audit
